### ISSUE TITLE
mpq fix md5 error

### ISSUE THREAD

**Issue by pisti094** [mewrnd/blizzconv#3]
The terminal says undefined md5.sum

**Comment by pisti094** [comment]
In mpqfix.go line 51 and 71

**Comment by mewmew** [comment]
Hi exorcizamus,

The top-level function `md5.Sum` was added in rev golang/go@4850f5d5ea5913af57c9ae37121ad88aba2d612c which became part of Go version 1.2.

From the [release notes](https://golang.org/doc/go1.2#minor_library_changes) of Go 1.2:
>  The crypto/md5 package adds a new Sum function to simplify hashing without sacrificing performance.

Try upgrading to version 1.2 or later and recompile `mpqfix`. Let me know how it works out.

Cheers /u

**Comment by pisti094** [comment]
:D how you get my real name ?  Looks like the problem solved  i installed ubuntu on my galaxy note 10.1 problem fixed after updateted the go langue to 1.2.1

**Comment by pisti094** [comment]
I currently working on the diablo android  the converter is great help for me

**Comment by mewmew** [comment]
> Looks like the problem solved

Perfect! I'll close the bug for now.

> I currently working on the diablo android port the converter is great help for me.

That's really cool. Glad that the conversion tools are of help to you. Will you by any chance release this project into the public? We'd be very interested in taking a look at it!

Cheers /u and i
