### ISSUE TITLE
Bad cl2 file (firema2.cl2)

### ISSUE THREAD

**Issue by wheybags** [mewrnd/blizzconv#6]
Hey, I know this repo is deprecated, but I found an issue with it (and in freeablo code based on it) that I thought you might like to know about. Fix from freeablo is here: https://github.com/wheybags/freeablo/commit/3e357e7992f6271e0031a0259c374e60b2a86e43#diff-2a4ad650a9f55493262d7412841c3366R643
blizzconv code in question is here: https://github.com/mewrnd/blizzconv/blob/master/images/cl2/type6.go#L44

It seems to me that firema2.cl2 has some rubbish data after each frame. When I placed a print in the setPixel function in your go code, it was dumping transparency blocks until around y=-42. This was ofc causing a segfault in freeablo since it's c++, but your go image class seemed to just ignore these writes?
It's not just a case of the image height being set wrong in the cl2 file, since the data stops in the middle of a line. My theory is it's just a corrupted file, like the other two (unravw and dmagew iirc).

**Comment by mewmew** [comment]
Hi Tom!

Thanks for reporting the issue :) Yeah, as you pointed out, blizzconv is superseeded by [sanctuary/formats](https://github.com/sanctuary/formats). So, I wanted to check how `formats` handled this CL2 file.

The issue that you outlined is indeed with the file being corrupt. Essentially what has happened is that the each frame of the `firema.cl2` animation contains 16384 pixels; which translates to 128x128 in size. However, the true width of this graphic is 96 pixels, so it all gets messed up.

`formats` handles this by simply specifying `96` as the width and ignoring any transparent overflow.

```json
	"monsters/fireman/firema.cl2": {
		// The contents of the archive header at offset 0 in firema.cl2:
		//    20 00 00 00  78 00 00 00  D0 00 00 00  28 01 00 00
		//    80 01 00 00  D8 01 00 00  30 02 00 00  88 02 00 00
		Nimgs: 8,
		// The contents of frame 0 at offset 0x2C0 in firema.cl2 starts with the
		// following header: 0A 00 E4 01 72 04 93 04 00 00.
		Header: 10,
		// NOTE: The frame width should be 128 according to 0x497E08, but 96
		// produces correct rendering.
		W: 96,
		// NOTE: Each frame contain 128x128 (16384) pixels, but the correct width
		// is 96.
		H: 171, // h = npixels/w = 16384/96 = 170.66
		Trns: []string{
			"monsters/monsters/general.trn", // ref: 0x49B6F8; Madburner, Warpfire Hellspawn
			"monsters/monsters/wftd.trn",    // ref: 0x49B6F8; Wrathfire the Doomed
		},
	},
```

How is life in Ireland? :) I'm currently enjoying student life in Korea during an exchange semester. We are having a most wonderful spring time with the cherry blossom.

Also, how is Freeablo coming along? :) I was really surprised to see Diablo 1 released on GoG last month!

Wish you all the best and a happy spring!

*glada kramar*
Robin

**Comment by wheybags** [comment]
Cool, I see you already know about the problem.
As for life in Ireland, I've actually moved to Prague, so I dunno :p
I'm hoping to release a new version of freeablo soon (as soon as I can get a release video together), project is slow but not dead :v
Enjoy your time in Korea! Also, a gentle reminder that freeablo can always use some more contributors :p

**Comment by mewmew** [comment]
> Cool, I see you already know about the problem. As for life in Ireland, I've actually moved to Prague, so I dunno :p I'm hoping to release a new version of freeablo soon (as soon as I can get a release video together), project is slow but not dead :v Enjoy your time in Korea! Also, a gentle reminder that freeablo can always use some more contributors :p

Oh, sweet! I love the Czech Republic! Went there last year for exploration and trekking. Also, like Prague.

Haha, glad to hear you are keeping the old beast alive :p How far along is game play now? I've been playing with Devilution as you may know. We are now very close to have a binary exact version of Diablo 1. Currently about 80% of the functions functions are binary exact (when using the same compiler as was used for Diablo 1).

Thanks, I do enjoy life i Korea. Right now, we have mid-terms though, so quite busy :p *nod* gentle reminder received ;)
